version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
    - .:/app
    ports: 
    - 8080:8080
    tty: true
    init: true
  db:
    restart: always
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306
    tty: true
    init: true