version: '3'
services:
  app:
    build: ./
    restart: always
    ports: 
    - 8080:8080
    volumes:
    - ./src:/app
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_app
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306