apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "flask_app"
        - name: MYSQL_USER
          value: "docker"
        - name: MYSQL_PASSWORD
          value: "docker"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data-mount
      volumes:
      - name: mysql-data-mount
        persistentVolumeClaim:
          claimName: mysql-data